<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXDWWY0V\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXDWWY0V/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXDWWY0V.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXDWWY0V\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXDWWY0V\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XDWWY0V',
    'container.build_id' => '70e8624b',
    'container.build_time' => 1649603331,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXDWWY0V');
