#index:
#    path: /
#    controller: App\Controller\DefaultController::index

produit:
    path: /produit
    defaults:
        _controller: FrameworkBundle:Template:template
        template: show.html.twig

reclamation:
    path: /reclamation
    defaults:
        _controller: FrameworkBundle:Template:template
        template: show.html.twig

fournisseur:
    path: /fournisseur
    defaults:
        _controller: FrameworkBundle:Template:template
        template: show.html.twig

commande:
    path: /commande
    defaults:
        _controller: FrameworkBundle:Template:template
        template: show.html.twig
categorie:
    path: /categorie
    defaults:
        _controller: FrameworkBundle:Template:template
        template: show.html.twig
        
raison:
    path: /raison
    defaults:
        _controller: FrameworkBundle:Template:template
        template: show.html.twig

captcha_routing:
    resource: "@CaptchaBundle/Resources/config/routing.yml"