<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3MI3rFg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3MI3rFg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3MI3rFg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3MI3rFg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3MI3rFg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3MI3rFg',
    'container.build_id' => '94303a93',
    'container.build_time' => 1651871046,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3MI3rFg');
