#index:
#    path: /
#    controller: App\Controller\DefaultController::index

inter:
  path: /intervenant
  defaults:
    _controller: FrameworkBundle:Template:template
    template: show.html.twig


event:
  path: /evenement
  defaults:
    _controller: FrameworkBundle:Template:template
    template: show.html.twig
